export const DEFAULT_CATEGORY_SITUATIONS: Record<string, string[]> = {
  "forgiveness-repentance": [
    "Prayer of Repentance",
    "Prayer for Peace After Conflict",
    "Prayer for Reconciliation in a Relationship",
    "Prayer for Restoring a Friendship",
    "Prayer for Restoring Trust",
    "Prayer for the Grace to Forgive Others",
    "Prayer to Let Go of Resentment",
    "Prayer When Someone Has Hurt You",
    "Prayer for Forgiving Oneself",
    "Prayer for Humility to Seek Forgiveness",
    "Prayer for Healing Broken Family Ties",
    "Prayer to Break Chains of Bitterness",
  ],
  "school-studies-exams": [
    "Prayer for Exam Peace and Focus",
    "Prayer for Clarity During Lectures",
    "Prayer for Memory and Retention",
    "Prayer for Academic Motivation",
    "Prayer Over Student Loan & Tuition Worry",
    "Prayer Before Submitting Assignments",
    "Prayer When Facing Academic Failure",
    "Prayer for Confidence in Presentations",
    "Prayer for Good Teachers and Mentors",
    "Prayer for Balance in Student Life",
  ],
  "work-career-business": [
    "Prayer for Job Interview Confidence",
    "Prayer for Promotion and Favor at Work",
    "Prayer for Business Breakthrough",
    "Prayer When Experiencing Workplace Burnout",
    "Prayer for Finding New Employment",
    "Prayer for Wisdom in Difficult Work Decisions",
    "Prayer for Ethical Business Integrity",
    "Prayer for Peaceful Relations with Boss and Coworkers",
    "Prayer for Creative Inspiration at Work",
    "Prayer for Work-Life Balance",
  ],
  "financial-difficulties": [
    "Prayer for Freedom from Debt",
    "Prayer for Provision in Times of Lack",
    "Prayer for Wisdom in Financial Management",
    "Prayer for Unexpected Financial Blessing",
    "Prayer to Overcome Financial Anxiety",
    "Prayer for Contentment and Generosity",
    "Prayer When Rent or Bills Are Due",
    "Prayer for Business Capital & Investment",
    "Prayer for Family Financial Security",
    "Prayer to Trust God as the Ultimate Provider",
  ],
  "family": [
    "Prayer for Protection Over Children",
    "Prayer for Marital Harmony and Love",
    "Prayer for Wayward Teenagers or Children",
    "Prayer for Elderly Parents' Health",
    "Prayer for Unity Among Siblings",
    "Prayer for Healing Generational Wounds",
    "Prayer for Peace in the Household",
    "Prayer for Expecting Parents and Babies",
    "Prayer for Single Parents",
    "Prayer for Grieving Families",
  ],
  "love-relationships": [
    "Prayer for Finding a Godly Partner",
    "Prayer for Courtship and Dating Wisdom",
    "Prayer for Healing After a Breakup",
    "Prayer to Strengthen Marriage Bonds",
    "Prayer for Purity and Self-Control",
    "Prayer for Healthy Boundaries in Relationships",
    "Prayer When Facing Loneliness",
    "Prayer for Patience in Waiting",
    "Prayer to Overcome Jealousy and Insecurity",
    "Prayer for Deep and Loyal Friendships",
  ],
  "health-healing": [
    "Prayer for Physical Healing from Disease",
    "Prayer for Mental Health and Inner Calm",
    "Prayer for Recovery After Surgery",
    "Prayer for Relief from Chronic Pain",
    "Prayer for Emotional Trauma and Grief",
    "Prayer for Doctors, Nurses, and Caregivers",
    "Prayer for Strength During Illness",
    "Prayer for Overcoming Addiction and Habits",
    "Prayer for Sound Sleep and Rest",
    "Prayer for Divine Life and Vitality",
  ],
  "protection-safety": [
    "Prayer for Safe Travel on Journeys",
    "Prayer for Spiritual Warfare and Deliverance",
    "Prayer for Home and Family Protection",
    "Prayer When Walking in Dangerous Places",
    "Prayer for Defense Against Slander and Evil",
    "Prayer Over Nightmares and Night Fears",
    "Prayer for Peace in the Nation and City",
    "Prayer for Angels of Protection",
    "Prayer to Stand Strong in God's Armor",
    "Prayer for Refuge in Times of Storms",
  ],
  "guidance-decisions": [
    "Prayer for Knowing God's Will",
    "Prayer for Making Big Life Choices",
    "Prayer for Discernment Between Good and Evil",
    "Prayer for Relocation or Moving Decisions",
    "Prayer for Clarity on Calling and Purpose",
    "Prayer for Peace in Confusion",
    "Prayer for Patience When God Seems Silent",
    "Prayer for Wise Counsel and Mentorship",
    "Prayer Before Signing Contracts or Agreements",
    "Prayer to Follow the Holy Spirit's Leading",
  ],
  "difficult-times-hardships": [
    "Prayer When Feeling Overwhelmed",
    "Prayer During Seasons of Grief and Loss",
    "Prayer When Life Feels Unfair",
    "Prayer for Perseverance in Suffering",
    "Prayer to Find Hope in the Dark",
    "Prayer for Deliverance from Depression",
    "Prayer When Feeling Abandoned by Friends",
    "Prayer to Anchor Faith in the Storm",
    "Prayer for Comfort in Loneliness",
    "Prayer for Strength to Endure One More Day",
  ],
  "gratitude-thanksgiving": [
    "Prayer of Gratitude for God's Faithfulness",
    "Prayer of Thanksgiving for Answered Prayers",
    "Prayer for Joy in the Morning",
    "Prayer Celebrating New Milestones",
    "Prayer for Daily Mercies and Blessings",
    "Prayer of Praise for Who God Is",
    "Prayer for a Grateful and Cheerful Heart",
    "Prayer Thanking God for Simple Joys",
    "Prayer for Divine Peace That Surpasses Understanding",
    "Prayer of Worship and Adoration",
  ],
};