export const MASTER_SITUATIONS_MAP: Record<string, string[]> = {
  forgiveness: [
    "Prayer for Forgiveness of Sins",
    "Prayer After Hurting Someone",
    "Prayer Before Asking Someone for Forgiveness",
    "Prayer for Forgiveness",
    "Prayer for Forgiving Yourself",
    "Prayer for Freedom from Bitterness",
    "Prayer for God's Mercy",
    "Prayer for Healing a Broken Relationship",
    "Prayer for Peace After Conflict",
    "Prayer for Reconciliation in a Relationship",
    "Prayer for Restoring Trust",
    "Prayer for Restoring a Friendship",
    "Prayer for a Fresh Start",
    "Prayer for a Repentant Heart",
    "Prayer for the Grace to Forgive Others",
    "Prayer of Repentance",
    "Prayer to Let Go of Resentment",
    "Prayer When Someone Has Hurt You",
    "Prayer for Humility to Seek Forgiveness",
    "Prayer to Break Chains of Bitterness",
    "Prayer for Healing Broken Family Ties",
  ],
  school: [
    "Prayer for Exam Peace and Focus",
    "Prayer for Clarity During Lectures",
    "Prayer for Memory and Retention",
    "Prayer for Academic Motivation",
    "Prayer Over Student Loan & Tuition Worry",
    "Prayer Before Submitting Assignments",
    "Prayer When Facing Academic Failure",
    "Prayer for Confidence in Presentations",
    "Prayer for Good Teachers and Mentors",
    "Prayer for Balance in Student Life",
    "Prayer Before an Important Exam",
    "Prayer for Overcoming Procrastination",
    "Prayer for Wisdom in Choosing a Major or Career",
    "Prayer for Group Projects and Teamwork",
    "Prayer for Relieving Study Stress and Fatigue",
    "Prayer for Godly Friendships at School",
    "Prayer for Thesis & Research Clarity",
    "Prayer for Academic Excellence",
  ],
  work: [
    "Prayer for Job Interview Confidence",
    "Prayer for Promotion and Favor at Work",
    "Prayer for Business Breakthrough",
    "Prayer When Experiencing Workplace Burnout",
    "Prayer for Finding New Employment",
    "Prayer for Wisdom in Difficult Work Decisions",
    "Prayer for Ethical Business Integrity",
    "Prayer for Peaceful Relations with Boss and Coworkers",
    "Prayer for Creative Inspiration at Work",
    "Prayer for Work-Life Balance",
    "Prayer for Divine Guidance in Career Direction",
    "Prayer Over Loss of Job or Unemployment",
    "Prayer for Godly Leadership and Humility",
    "Prayer for Diligence and Focus at Work",
    "Prayer for Fair Treatment and Justice in the Workplace",
    "Prayer for Blessing Over Business Clients and Customers",
    "Prayer for Starting a New Business Venture",
    "Prayer for Stress Relief During Work Deadlines",
  ],
  finance: [
    "Prayer for Freedom from Debt",
    "Prayer for Provision in Times of Lack",
    "Prayer for Wisdom in Financial Management",
    "Prayer for Unexpected Financial Blessing",
    "Prayer to Overcome Financial Anxiety",
    "Prayer for Contentment and Generosity",
    "Prayer When Rent or Bills Are Due",
    "Prayer for Business Capital & Investment",
    "Prayer for Family Financial Security",
    "Prayer to Trust God as the Ultimate Provider",
    "Prayer When Facing Financial Crisis",
    "Prayer to Break Scarcity Mindsets",
    "Prayer for Wisdom in Budgeting and Spending",
    "Prayer for Protection Over Assets and Income",
    "Prayer for Integrity in Financial Dealings",
    "Prayer for Tithing and Cheerful Giving",
    "Prayer for Emergency Financial Relief",
    "Prayer When Facing Loss of Income",
  ],
  family: [
    "Prayer for Protection Over Children",
    "Prayer for Marital Harmony and Love",
    "Prayer for Wayward Teenagers or Children",
    "Prayer for Elderly Parents' Health",
    "Prayer for Unity Among Siblings",
    "Prayer for Healing Generational Wounds",
    "Prayer for Peace in the Household",
    "Prayer for Expecting Parents and Babies",
    "Prayer for Single Parents",
    "Prayer for Grieving Families",
    "Prayer for Salvation of Family Members",
    "Prayer for Extended Family Relationships",
    "Prayer When Parents Are Aging",
    "Prayer Over Family Conflict and Estrangement",
    "Prayer for Blessing Over the Family Home",
    "Prayer for In-Law Relationships",
  ],
  love: [
    "Prayer for Finding a Godly Partner",
    "Prayer for Courtship and Dating Wisdom",
    "Prayer for Healing After a Breakup",
    "Prayer to Strengthen Marriage Bonds",
    "Prayer for Purity and Self-Control",
    "Prayer for Healthy Boundaries in Relationships",
    "Prayer When Facing Loneliness",
    "Prayer for Patience in Waiting",
    "Prayer to Overcome Jealousy and Insecurity",
    "Prayer for Deep and Loyal Friendships",
    "Prayer for Communication in Relationships",
    "Prayer When Feeling Unloved or Rejected",
    "Prayer for Trust and Vulnerability",
    "Prayer for Discernment in Romantic Pursuits",
    "Prayer for Honoring God Through Singleness",
    "Prayer for Healing Heartbreak and Betrayal",
  ],
  health: [
    "Prayer for Physical Healing from Disease",
    "Prayer for Mental Health and Inner Calm",
    "Prayer for Recovery After Surgery",
    "Prayer for Relief from Chronic Pain",
    "Prayer for Emotional Trauma and Grief",
    "Prayer for Doctors, Nurses, and Caregivers",
    "Prayer for Strength During Illness",
    "Prayer for Overcoming Addiction and Habits",
    "Prayer for Sound Sleep and Rest",
    "Prayer for Divine Life and Vitality",
    "Prayer for Deliverance from Anxiety and Panic",
    "Prayer for a Sick Child or Family Member",
    "Prayer When Receiving a Difficult Medical Diagnosis",
    "Prayer for Renewal of Strength and Energy",
    "Prayer for Spiritual Healing of the Soul",
    "Prayer for Immune System Strengthening",
  ],
  protection: [
    "Prayer for Safe Travel on Journeys",
    "Prayer for Spiritual Warfare and Deliverance",
    "Prayer for Home and Family Protection",
    "Prayer When Walking in Dangerous Places",
    "Prayer for Defense Against Slander and Evil",
    "Prayer Over Nightmares and Night Fears",
    "Prayer for Peace in the Nation and City",
    "Prayer for Angels of Protection",
    "Prayer to Stand Strong in God's Armor",
    "Prayer for Refuge in Times of Storms",
    "Prayer for Protection from Harmful Influences",
    "Prayer for Security at Night",
    "Prayer Against Enemy Schemes and Traps",
    "Prayer for Divine Guidance in Dangerous Times",
    "Prayer for Protection at Work and School",
  ],
  guidance: [
    "Prayer for Knowing God's Will",
    "Prayer for Making Big Life Choices",
    "Prayer for Discernment Between Good and Evil",
    "Prayer for Relocation or Moving Decisions",
    "Prayer for Clarity on Calling and Purpose",
    "Prayer for Peace in Confusion",
    "Prayer for Patience When God Seems Silent",
    "Prayer for Wise Counsel and Mentorship",
    "Prayer Before Signing Contracts or Agreements",
    "Prayer to Follow the Holy Spirit's Leading",
    "Prayer for Direction at a Crossroads",
    "Prayer for Courage to Step Into the Unknown",
    "Prayer for Closing Wrong Doors and Opening Right Ones",
    "Prayer for Wisdom When Overwhelmed by Choices",
    "Prayer for Spiritual Sensitivity and Insight",
  ],
  hardship: [
    "Prayer When Feeling Overwhelmed",
    "Prayer During Seasons of Grief and Loss",
    "Prayer When Life Feels Unfair",
    "Prayer for Perseverance in Suffering",
    "Prayer to Find Hope in the Dark",
    "Prayer for Deliverance from Depression",
    "Prayer When Feeling Abandoned by Friends",
    "Prayer to Anchor Faith in the Storm",
    "Prayer for Comfort in Loneliness",
    "Prayer for Strength to Endure One More Day",
    "Prayer When Feeling Hopeless",
    "Prayer When Waiting for a Miracle",
    "Prayer When Tears Won't Stop",
    "Prayer for Rest in the Middle of Turmoil",
    "Prayer for God's Presence in Desolation",
    "Prayer When Questioning Your Faith",
  ],
  gratitude: [
    "Prayer of Gratitude for God's Faithfulness",
    "Prayer of Thanksgiving for Answered Prayers",
    "Prayer for Joy in the Morning",
    "Prayer Celebrating New Milestones",
    "Prayer for Daily Mercies and Blessings",
    "Prayer of Praise for Who God Is",
    "Prayer for a Grateful and Cheerful Heart",
    "Prayer Thanking God for Simple Joys",
    "Prayer for Divine Peace That Surpasses Understanding",
    "Prayer of Worship and Adoration",
    "Prayer of Gratitude for God's Unconditional Love",
    "Prayer of Thanksgiving for Spiritual Growth",
    "Prayer of Praise for God's Provision and Grace",
    "Prayer for Remembering Past Deliverances",
    "Prayer of Thanksgiving for Answered Intercessions",
  ],
};

export function getSituationsForCategory(category?: { name?: string; slug?: string } | null): string[] {
  if (!category) return [];
  const text = `${category.name ?? ""} ${category.slug ?? ""}`.toLowerCase();

  if (text.includes("financ") || text.includes("money") || text.includes("debt")) return MASTER_SITUATIONS_MAP.finance!;
  if (text.includes("forgiv") || text.includes("repent") || text.includes("reconcil")) return MASTER_SITUATIONS_MAP.forgiveness!;
  if (text.includes("school") || text.includes("stud") || text.includes("exam") || text.includes("acad")) return MASTER_SITUATIONS_MAP.school!;
  if (text.includes("work") || text.includes("career") || text.includes("business") || text.includes("job")) return MASTER_SITUATIONS_MAP.work!;
  if (text.includes("famil") || text.includes("parent") || text.includes("child")) return MASTER_SITUATIONS_MAP.family!;
  if (text.includes("love") || text.includes("relation") || text.includes("marri") || text.includes("dating")) return MASTER_SITUATIONS_MAP.love!;
  if (text.includes("health") || text.includes("heal") || text.includes("sick")) return MASTER_SITUATIONS_MAP.health!;
  if (text.includes("protect") || text.includes("safe") || text.includes("secur")) return MASTER_SITUATIONS_MAP.protection!;
  if (text.includes("guid") || text.includes("decis") || text.includes("wisdom")) return MASTER_SITUATIONS_MAP.guidance!;
  if (text.includes("difficult") || text.includes("hardship") || text.includes("grief") || text.includes("depress")) return MASTER_SITUATIONS_MAP.hardship!;
  if (text.includes("gratitud") || text.includes("thank") || text.includes("praise")) return MASTER_SITUATIONS_MAP.gratitude!;

  return [];
}